###########################################################  Makefile
# CS570, Summer 2014, a3
# Jose Paterno, Jonathan Dabu, masc1418, masc1417
###########################################################
EXEC = a3
CC = g++       ###  or use cc / g++ / gcc   ###

$(EXEC):
	$(CC) -o $(EXEC) child_process_sim.cpp 
	rm -f *.o

clean:
	rm -f *.o core a.out $(EXEC) 

#######################[ EOF: Makefile ]###################
